### PR TITLE
Fix image embed in README

### LINKED ISSUE #8: readme snapshots
seems the linked image in the readme does not exist

grafik

### PR DESCRIPTION
**Pull request by svenluijten**
I've uploaded the `test1.png` from this repository's `tests` folder to GitHub's CDN (by just dragging it into an issue comment box and copying the resulting URL). 

Fixes #8.

### CODE REVIEW

**Comment by simonhamp** [comment]
I must have it cached. The problem is that `test/test.png` no longer exists.

The image you've selected doesn't represent what the code above it would have generated.

perhaps we need an `examples` folder separate from tests that we can use to show folks what can be achieved?

**Comment by svenluijten** [comment]
I like the `examples` folder! But also #5 would also create examples in `__snapshots__`.

**Comment by simonhamp** [comment]
True. That may be a more reliable URL to pin this to as the package evolves... let's do that

**Comment by simonhamp** [comment]
I've fixed this directly using the relevant image from the `__snapshots__` folder

**Pull request closed without merging**
